language: objective-c
before_install:
  - gem install cocoapods
before_script:
  - brew update
  - brew updade xctool
  - cd Example
  - pod install
script: 
- xctool test -workspace msgpack.xcworkspace -scheme msgpack -sdk iphonesimulator7.1 ONLY_ACTIVE_ARCH=NO
