language: objective-c
before_install:
  - gem install cocoapods
before_script:
  - brew update
  - brew upgrade xctool
  - cd Example
  - pod install
script: 
- xctool test -workspace msgpack.xcworkspace -scheme msgpack -sdk iphonesimulator -destination 'name=iPhone Retina (4-inch 64-bit),OS=7.1'
